blueprints/recipes/__init__.py
from flask import Blueprint

bp = Blueprint('recipes', __name__)

from blueprints.recipes import routes

blueprints/recipes/routes.py
from flask import request, render_template, abort, flash, redirect, url_for

from persistence.model.recipe import Recipe
from persistence.repository.recipe import RecipeRepository
from blueprints.forms import EntityForm
from blueprints.recipes import bp
from security.decorators import has_admin_role


@bp.route('/')
def list_all():
    if request.args.get('search'):
        recipes = RecipeRepository.find_by_name(request.args.get('search'))
    else:
        recipes = RecipeRepository.find_all()

    return render_template('recipes/list.html', recipes=recipes)


@bp.route('/view/<int:recipe_id>')
def view(recipe_id):
    recipe = RecipeRepository.find_by_id(recipe_id) or abort(404)

    return render_template('recipes/view.html', recipe=recipe)


@bp.route('/create', methods=('GET', 'POST'))
@has_admin_role
def create():
    recipe = Recipe()
    form = EntityForm(recipe)

    if form.validate_on_submit():
        try:
            RecipeRepository.save(recipe)
            flash('Recipe created.')

            return redirect(url_for('recipes.list_all'))
        except Exception as err:
            flash(str(err))

    return render_template('recipes/form.html', form=form)


@bp.route('/edit/<int:recipe_id>', methods=('GET', 'POST'))
@has_admin_role
def edit(recipe_id):
    recipe = RecipeRepository.find_by_id(recipe_id) or abort(404)
    form = EntityForm(recipe)

    if form.validate_on_submit():
        try:
            RecipeRepository.save(recipe)
            flash('Recipe saved.')

            return redirect(url_for('recipes.edit', recipe_id=recipe.recipe_id))
        except Exception as err:
            flash(str(err))

    return render_template('recipes/form.html', form=form)


@bp.route('/delete/<int:recipe_id>', methods=('POST',))
@has_admin_role
def delete(recipe_id):
    RecipeRepository.find_by_id(recipe_id) or abort(404)

    try:
        RecipeRepository.delete_by_id(recipe_id)
        flash('Recipe deleted.')
    except Exception as err:
        flash(str(err))

    return redirect(url_for('recipes.list_all'))

templates/recipes/form.html
{% extends 'base.html' %}

{% set recipe = form.entity %}

{% block main %}
    <h2>{{ 'Create' if form.create_form else 'Edit' }} recipe</h2>

    {% if form.errors %}
        <ul>
            {% for error in form.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="post">
        <table>
            <tbody>
            <tr>
                <th>
                    <label for="category">Category</label>
                </th>
                <td>
                    <input name="category"
                           type="text"
                           class="form-control"
                           id="category"
                           value="{{ recipe.category }}" required>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="name">Name</label>
                </th>
                <td>
                    <input name="name"
                           type="text"
                           class="form-control"
                           id="name"
                           value="{{ recipe.name }}" required>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="description">Description</label>
                </th>
                <td>
                    <textarea name="description"
                              class="form-control"
                              id="description">{{ recipe.description }}</textarea>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="difficulty">Difficulty</label>
                </th>
                <td>
                    <select name="difficulty" class="form-control" id="difficulty" required>
                        <option value="1"{{ ' selected' if recipe.difficulty == 1 else '' }}>
                            ★☆☆☆☆ (Very easy)
                        </option>
                        <option value="2"{{ ' selected' if recipe.difficulty == 2 else '' }}>
                            ★★☆☆☆ (Easy)
                        </option>
                        <option value="3"{{ ' selected' if recipe.difficulty == 3 else '' }}>
                            ★★★☆☆ (Medium)
                        </option>
                        <option value="4"{{ ' selected' if recipe.difficulty == 4 else '' }}>
                            ★★★★☆ (Difficult)
                        </option>
                        <option value="5"{{ ' selected' if recipe.difficulty == 5 else '' }}>
                            ★★★★★ (Very difficult)
                        </option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    {% if form.create_form %}
                        <button type="submit" class="btn btn-primary" onclick="return confirm('Create recipe?')">
                            Create
                        </button>
                    {% else %}
                        <button type="submit" class="btn btn-primary" onclick="return confirm('Save recipe?')">
                            Save
                        </button>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ url_for('recipes.list_all') }}" class="btn btn-secondary">Cancel</a>
                </td>
            </tr>
            </tbody>
        </table>
    </form>
{% endblock %}

templates/recipes/list.html
{% extends 'base.html' %}

{% block search %}
    <form>
        <div class="row">
            <div class="col-auto">
                <input name="search" type="text" class="form-control" id="search" value="{{ request.args.get('search', '') }}">
            </div>
            <div class="col-auto">
                <label for="search"><button type="submit" class="btn btn-primary">Search</button></label>
            </div>
        </div>
    </form>
{% endblock %}

{% block main %}
    <h1>Recipes</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Category</th>
            <th>Name</th>
            <th>Difficulty</th>
            {% if not has_admin_role() %}
                <th></th>
            {% else %}
                <th colspan="3"></th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for recipe in recipes %}
            <tr>
                <td>{{ recipe.category }}</td>
                <td>{{ recipe.name }}</td>
                <td>
                    {{ '★' * recipe.difficulty }}{{ '☆' * (5 - recipe.difficulty) }}
                    ({{ recipe.difficulty_description }})
                </td>
                <td>
                    <a href="{{ url_for('recipes.view', recipe_id=recipe.recipe_id) }}" class="btn btn-secondary">
                        View
                    </a>
                </td>
                {% if has_admin_role() %}
                    <td>
                        <a href="{{ url_for('recipes.edit', recipe_id=recipe.recipe_id) }}" class="btn btn-primary">
                            Edit
                        </a>
                    </td>
                    <td>
                        <form method="post" action="{{ url_for('recipes.delete', recipe_id=recipe.recipe_id) }}">
                            <button type="submit" class="btn btn-danger" onclick="return confirm('Delete recipe?')">
                                Delete
                            </button>
                        </form>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if has_admin_role() %}
        <p><a href="{{ url_for('recipes.create') }}" class="btn btn-primary">Create recipe</a></p>
    {% endif %}
{% endblock %}

templates/recipes/view.html
{% extends 'base.html' %}

{% block main %}
    <h2>{{ recipe.name }}</h2>
    <table class="table table-striped">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ recipe.recipe_id }}</td>
        </tr>
        <tr>
            <th>Category</th>
            <td>{{ recipe.category }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ recipe.name }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ recipe.description }}</td>
        </tr>
        <tr>
            <th>Difficulty</th>
            <td>
                {{ '★' * recipe.difficulty }}{{ '☆' * (5 - recipe.difficulty) }}
                ({{ recipe.difficulty_description }})
            </td>
        </tr>
        </tbody>
    </table>
    <p><a href="{{ url_for('recipes.list_all') }}" class="btn btn-primary">Close</a></p>
{% endblock %}