blueprints/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from blueprints.users import routes

blueprints/users/routes.py
from flask import render_template, abort, flash, redirect, url_for

from persistence.model.user import User
from persistence.repository.user import UserRepository
from blueprints.forms import EntityForm
from blueprints.users import bp
from security.decorators import is_fully_authenticated, has_admin_role


@bp.route('/')
@is_fully_authenticated
def list_all():
    return render_template('users/list.html', users=UserRepository.find_all())


@bp.route('/create', methods=('GET', 'POST'))
@has_admin_role
def create():
    user = User()
    form = EntityForm(user)

    if form.validate_on_submit():
        try:
            UserRepository.save(user)
            flash('User created.')

            return redirect(url_for('users.list_all'))
        except Exception as err:
            flash(str(err))

    return render_template('users/form.html', form=form)


@bp.route('/edit/<int:user_id>', methods=('GET', 'POST'))
@has_admin_role
def edit(user_id):
    user = UserRepository.find_by_id(user_id) or abort(404)
    form = EntityForm(user)

    if form.validate_on_submit():
        try:
            UserRepository.save(user)
            flash('User saved.')

            return redirect(url_for('users.edit', user_id=user.user_id))
        except Exception as err:
            flash(str(err))

    return render_template('users/form.html', form=form)


@bp.route('/delete/<int:user_id>', methods=('POST',))
@has_admin_role
def delete(user_id):
    UserRepository.find_by_id(user_id) or abort(404)

    try:
        UserRepository.delete_by_id(user_id)
        flash('User deleted.')
    except Exception as err:
        flash(str(err))

    return redirect(url_for('users.list_all'))

templates/users/form.html
{% extends 'base.html' %}

{% set user = form.entity %}

{% block main %}
    <h2>{{ 'Create' if form.create_form else 'Edit' }} user</h2>

    {% if form.errors %}
        <ul>
            {% for error in form.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="post">
        <table>
            <tbody>
            <tr>
                <th>
                    <label for="username">Username</label>
                </th>
                <td>
                    <input name="username"
                           type="text"
                           class="form-control"
                           id="username"
                           value="{{ user.username }}" required>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="password">Password</label>
                </th>
                <td>
                    <input name="password"
                           type="password"
                           class="form-control"
                           id="password"{{ ' required' if form.create_form else '' }}>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="role">Role</label>
                </th>
                <td>
                    <select name="role" class="form-control" id="role" required>
                        <option value="user"{{ ' selected' if user.role == 'user' else '' }}>
                            USER
                        </option>
                        <option value="admin"{{ ' selected' if user.role == 'admin' else '' }}>
                            ADMIN
                        </option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    {% if form.create_form %}
                        <button type="submit" class="btn btn-primary" onclick="return confirm('Create user?')">
                            Create
                        </button>
                    {% else %}
                        <button type="submit" class="btn btn-primary" onclick="return confirm('Save user?')">
                            Save
                        </button>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ url_for('users.list_all') }}" class="btn btn-secondary">Cancel</a>
                </td>
            </tr>
            </tbody>
        </table>
    </form>
{% endblock %}

templates/users/list.html
{% extends 'base.html' %}

{% block main %}
    <h1>Users</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Username</th>
            <th>Role</th>
            {% if has_admin_role() %}
                <th colspan="2"></th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.role }}</td>
                {% if has_admin_role() %}
                    <td>
                        <a href="{{ url_for('users.edit', user_id=user.user_id) }}" class="btn btn-primary">
                            Edit
                        </a>
                    </td>
                    <td>
                        <form method="post" action="{{ url_for('users.delete', user_id=user.user_id) }}">
                            <button type="submit" class="btn btn-danger" onclick="return confirm('Delete user?')">
                                Delete
                            </button>
                        </form>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if has_admin_role() %}
        <p><a href="{{ url_for('users.create') }}" class="btn btn-primary">Create user</a></p>
    {% endif %}
{% endblock %}